name: fake-news-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.23.5
  - pytorch=1.13.1
  - cudatoolkit=11.7
  - tensorflow=2.12.0
  - scikit-learn=1.3.0
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pandas=2.0.3
  - scipy=1.10.1
  - networkx=3.1
  - tqdm=4.65.0
  - pip:
    - torch==1.13.1
    - --find-links https://data.pyg.org/whl/torch-1.13.0+cu117.html
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - torch-geometric==2.3.0
    - transformers==4.34.0
    - vaderSentiment==3.3.2
    - newspaper3k==0.2.8
    - botometer==1.6
    - python-dotenv==1.0.0
